#Day02 Analysis
- 72 bad rows removed (negative fares, zero distance, zero passengers, negative duration)
- 99,928 clean rows remaining
- Outlier threshold for fare: $41.91
- Busiest hour: 19th
- Busiest day: Saturday
- Data quality: 99.93% clean

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd

df = pd.read_csv(
    '/content/drive/MyDrive/datasets/yellow_tripdata_2015-01.csv',
    nrows=100000
)
print("shape:", df.shape)
print("\ncolumns:\n", df.columns.tolist())
df.head()

shape: (100000, 19)

columns:
 ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'pickup_longitude', 'pickup_latitude', 'RateCodeID', 'store_and_fwd_flag', 'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount']

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2015-01-15 19:05:39,2015-01-15 19:23:42,1,1.59,-73.993896,40.750111,1,N,-73.974785,40.750618,1,12.0,1.0,0.5,3.25,0.0,0.3,17.05
1,1,2015-01-10 20:33:38,2015-01-10 20:53:28,1,3.30,-74.001648,40.724243,1,N,-73.994415,40.759109,1,14.5,0.5,0.5,2.00,0.0,0.3,17.80
2,1,2015-01-10 20:33:38,2015-01-10 20:43:41,1,1.80,-73.963341,40.802788,1,N,-73.951820,40.824413,2,9.5,0.5,0.5,0.00,0.0,0.3,10.80
3,1,2015-01-10 20:33:39,2015-01-10 20:35:31,1,0.50,-74.009087,40.713818,1,N,-74.004326,40.719986,2,3.5,0.5,0.5,0.00,0.0,0.3,4.80
4,1,2015-01-10 20:33:39,2015-01-10 20:52:58,1,3.00,-73.971176,40.762428,1,N,-74.004181,40.742653,2,15.0,0.5,0.5,0.00,0.0,0.3,16.30

#Basic Data Exploration

In [23]:
print("\nNull Count:\n", df.isnull().sum())
print("\nDuplicates:", df.duplicated().sum())
print("\nData types:\n", df.dtypes)
df.describe()
#Data is already cleaned

Null Count:
 VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
pickup_longitude         0
pickup_latitude          0
RateCodeID               0
store_and_fwd_flag       0
dropoff_longitude        0
dropoff_latitude         0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
trip_duration            0
trip_duration_mins       0
pickup_hour              0
pickup_day               0
pickup_month             0
dtype: int64

Duplicates: 0

Data types:
 VendorID                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   int64
trip_distance                   float64
pickup_longitude                float64
pickup_latitude                 float64
RateCodeID                        int64
store_and_fwd_flag               object
dropoff_longitude               float64
dropoff_latitude                float64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
trip_duration                   float64
trip_duration_mins              float64
pickup_hour                       int32
pickup_day                       object
pickup_month                      int32
dtype: object

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,dropoff_longitude,dropoff_latitude,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,trip_duration,trip_duration_mins,pickup_hour,pickup_month
count,100000.000000,100000,100000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.0
mean,1.516030,2015-01-16 20:09:30.122819840,2015-01-16 20:22:31.837260032,1.66818,2.766231,-72.575004,39.979964,1.036410,-72.617655,40.004596,...,0.320095,0.497570,1.544944,0.247435,0.284331,14.775254,781.714440,13.028577,13.808620,1.0
min,1.000000,2015-01-01 00:09:45,2015-01-01 00:11:36,0.00000,0.000000,-80.592438,0.000000,1.000000,-74.393951,0.000000,...,-1.000000,-0.500000,-58.090000,-5.330000,0.000000,-139.700000,0.000000,0.000000,0.000000,1.0
25%,1.000000,2015-01-09 15:15:01,2015-01-09 15:25:23.750000128,1.00000,1.000000,-73.991592,40.736145,1.000000,-73.991150,40.734630,...,0.000000,0.500000,0.000000,0.000000,0.300000,8.190000,366.000000,6.100000,9.000000,1.0
50%,2.000000,2015-01-16 17:42:12,2015-01-16 17:53:31,1.00000,1.650000,-73.981461,40.753529,1.000000,-73.979805,40.753777,...,0.000000,0.500000,1.000000,0.000000,0.300000,11.160000,597.000000,9.950000,15.000000,1.0
75%,2.000000,2015-01-23 21:03:18,2015-01-23 21:15:37.750000128,2.00000,2.990000,-73.966423,40.767785,1.000000,-73.962532,40.768926,...,0.500000,0.500000,2.080000,0.000000,0.300000,16.300000,946.000000,15.770000,19.000000,1.0
max,2.000000,2015-01-31 23:57:12,2015-02-01 23:36:02,9.00000,181.400000,0.000000,41.105976,99.000000,0.000000,41.220047,...,7.000000,0.500000,100.000000,95.330000,0.300000,270.130000,86343.000000,1439.050000,23.000000,1.0
std,0.499745,NaN,NaN,1.32375,3.438196,10.078630,5.553303,0.516534,9.925810,5.468119,...,0.373561,0.036798,2.286399,1.281223,0.066747,12.235517,1996.231148,33.270525,6.290664,0.0

#Fixing datetime column

In [9]:
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [13]:
#Trip Duaration
df['trip_duration_mins'] = round((df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds() / 60,2)
print(df[['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'trip_duration_mins']].head())

  tpep_pickup_datetime tpep_dropoff_datetime  trip_duration_mins
0  2015-01-15 19:05:39   2015-01-15 19:23:42               18.05
1  2015-01-10 20:33:38   2015-01-10 20:53:28               19.83
2  2015-01-10 20:33:38   2015-01-10 20:43:41               10.05
3  2015-01-10 20:33:39   2015-01-10 20:35:31                1.87
4  2015-01-10 20:33:39   2015-01-10 20:52:58               19.32

#Extraction of time features

In [15]:
df['pickup_hour'] = df['tpep_pickup_datetime'].dt.hour
df['pickup_day'] = df['tpep_pickup_datetime'].dt.day_name()
df['pickup_month'] = df['tpep_pickup_datetime'].dt.month
print(df[['tpep_pickup_datetime', 'pickup_hour', 'pickup_day', 'pickup_month']].head())

  tpep_pickup_datetime  pickup_hour pickup_day  pickup_month
0  2015-01-15 19:05:39           19   Thursday             1
1  2015-01-10 20:33:38           20   Saturday             1
2  2015-01-10 20:33:38           20   Saturday             1
3  2015-01-10 20:33:39           20   Saturday             1
4  2015-01-10 20:33:39           20   Saturday             1

#Analysis

In [16]:
#spotting impossible values
print("Fare amount min:", df['fare_amount'].min())
print("Trip distance min:", df['trip_distance'].min())
print("Passenger count min:", df['passenger_count'].min())
print("Trip duration min:", df['trip_duration_mins'].min())
print("\nFare amount max:", df['fare_amount'].max())
print("Trip distance max:", df['trip_distance'].max())
print("Passenger count max:", df['passenger_count'].max())
print("Trip duration max:", df['trip_duration_mins'].max())

Fare amount min: -138.9
Trip distance min: 0.0
Passenger count min: 0
Trip duration min: 0.0

Fare amount max: 234.0
Trip distance max: 181.4
Passenger count max: 9
Trip duration max: 1439.05

In [17]:
#bad rows
print("Negative fares:", len(df[df['fare_amount'] <= 0]))
print("Zero distance:", len(df[df['trip_distance'] <= 0]))
print("Zero passengers:", len(df[df['passenger_count'] <= 0]))
print("Negative duration:", len(df[df['trip_duration_mins'] <= 0]))
print("Too many passengers:", len(df[df['passenger_count'] > 6]))

Negative fares: 72
Zero distance: 634
Zero passengers: 65
Negative duration: 105
Too many passengers: 1

In [18]:
#Handling bad values
original = len(df)
df_clean = df[
    df['fare_amount'] > 0
    & (df['trip_distance'] > 0)
    & (df['passenger_count'] > 0)
    & (df['trip_duration_mins'] > 0)
]

print(f"Original rows: {original}")
print(f"Cleaned rows: {len(df_clean)}")
print(f"Removed rows: {original - len(df_clean)}")

Original rows: 100000
Cleaned rows: 99928
Removed rows: 72

#Outlier Detection

In [21]:
mean_fare = df_clean['fare_amount'].mean()
std_fare = df_clean['fare_amount'].std()

outliers = df_clean[df_clean['fare_amount'] > mean_fare + 3*std_fare]

print(f"fare Outliers: {len(outliers)}")
print(f"Outlier Threshold: ${mean_fare + 3*std_fare:.2f}")

fare Outliers: 2747
Outlier Threshold: $41.91

In [22]:
#Quick Insights
print("Busiest hour:\n", df_clean.groupby('pickup_hour').size().sort_values(ascending=False).head(3))
print("\nBusiest day:\n", df_clean.groupby('pickup_day').size().sort_values(ascending=False))
print("\nAvg fare by passenger count:\n", df_clean.groupby('passenger_count')['fare_amount'].mean().round(2))

Busiest hour:
 pickup_hour
19    7118
18    6559
14    5839
dtype: int64

Busiest day:
 pickup_day
Saturday     18451
Thursday     16631
Friday       16589
Wednesday    14871
Tuesday      11876
Sunday       11206
Monday       10304
dtype: int64

Avg fare by passenger count:
 passenger_count
0    10.31
1    11.74
2    12.56
3    12.18
4    12.21
5    11.64
6    11.87
9     9.80
Name: fare_amount, dtype: float64